"""Tests for the ingestion service.

FastAPI's TestClient exercises the endpoint in-process — no server, no network,
no real API. We assert the contract: a valid InferenceLog is accepted (200), a
malformed one is rejected (422) before our handler ever runs.
"""

from fastapi.testclient import TestClient

from ingestion.main import app

client = TestClient(app)

VALID_LOG = {
    "provider": "anthropic",
    "model": "claude-sonnet-5",
    "status": "success",
    "started_at": "2026-01-01T00:00:00Z",
    "ended_at": "2026-01-01T00:00:01Z",
    "latency_ms": 123.4,
}


def test_valid_payload_is_accepted():
    resp = client.post("/logs", json=VALID_LOG)
    assert resp.status_code == 200
    body = resp.json()
    assert body["status"] == "received"
    assert "event_id" in body  # generated by default_factory when not supplied


def test_malformed_payload_is_rejected():
    bad = {"provider": "anthropic"}  # missing required fields (model, status, ...)
    resp = client.post("/logs", json=bad)
    assert resp.status_code == 422
